<?php 
/* 	
If you see this text in your browser, PHP is not configured correctly on this hosting provider. 
Contact your hosting provider regarding PHP configuration for your site.

PHP file generated by Adobe Muse CC 2018.1.0.386
*/

require_once('form_process.php');

$form = array(
	'subject' => 'Onboarding Formular Übermittlung',
	'heading' => 'Neue Formularübermittlung',
	'success_redirect' => 'dashboard.html',
	'resources' => array(
		'checkbox_checked' => 'Aktiviert',
		'checkbox_unchecked' => 'Nicht aktiviert',
		'submitted_from' => 'Von Website übermitteltes Formular: %s',
		'submitted_by' => 'Besucher-IP-Adresse: %s',
		'too_many_submissions' => 'Zu viele Sendungen in letzter Zeit von dieser IP',
		'failed_to_send_email' => 'E-Mail konnte nicht gesendet werden',
		'invalid_reCAPTCHA_private_key' => 'Ungültiger privater reCAPTCHA-Schlüssel.',
		'invalid_reCAPTCHA2_private_key' => 'Ungültiger privater reCAPTCHA 2.0-Schlüssel.',
		'invalid_reCAPTCHA2_server_response' => 'Ungültige private reCAPTCHA 2.0-Server-Reaktionszeit.',
		'invalid_field_type' => 'Unbekannter Feldtyp „%s“.',
		'invalid_form_config' => 'Die Konfiguration im Feld „%s“ ist ungültig.',
		'unknown_method' => 'Unbekannte Serveranfragemethode'
	),
	'email' => array(
		'from' => 'adresse@einsetzen.de',
		'to' => 'adresse@einsetzen.de'
	),
	'fields' => array(
		'custom_U787' => array(
			'order' => 3,
			'type' => 'string',
			'label' => 'Vorname',
			'required' => true,
			'errors' => array(
				'required' => 'Feld „Vorname“ ist erforderlich.'
			)
		),
		'Email' => array(
			'order' => 4,
			'type' => 'email',
			'label' => 'Nachname',
			'required' => true,
			'errors' => array(
				'required' => 'Feld „Nachname“ ist erforderlich.',
				'format' => 'Die E-Mail-Adresse in Feld „Nachname“ ist ungültig.'
			)
		),
		'custom_U954' => array(
			'order' => 5,
			'type' => 'string',
			'label' => 'Privatanschrift',
			'required' => true,
			'errors' => array(
				'required' => 'Feld „Privatanschrift“ ist erforderlich.'
			)
		),
		'custom_U966' => array(
			'order' => 6,
			'type' => 'string',
			'label' => 'Ort',
			'required' => true,
			'errors' => array(
				'required' => 'Feld „Ort“ ist erforderlich.'
			)
		),
		'custom_U990' => array(
			'order' => 7,
			'type' => 'string',
			'label' => 'PLZ',
			'required' => true,
			'errors' => array(
				'required' => 'Feld „PLZ“ ist erforderlich.'
			)
		),
		'custom_U1002' => array(
			'order' => 8,
			'type' => 'string',
			'label' => 'Land',
			'required' => true,
			'errors' => array(
				'required' => 'Feld „Land“ ist erforderlich.'
			)
		),
		'custom_U1014' => array(
			'order' => 10,
			'type' => 'string',
			'label' => 'Wähle Deinen Benutzernamen/ Nicknamen',
			'required' => true,
			'errors' => array(
				'required' => 'Feld „Wähle Deinen Benutzernamen/ Nicknamen“ ist erforderlich.'
			)
		),
		'custom_U1026' => array(
			'order' => 1,
			'type' => 'checkbox',
			'label' => 'Herr',
			'required' => true,
			'errors' => array(
				'required' => 'Feld „Herr“ ist erforderlich.'
			)
		),
		'custom_U1083' => array(
			'order' => 2,
			'type' => 'checkbox',
			'label' => 'Frau',
			'required' => true,
			'errors' => array(
				'required' => 'Feld „Frau“ ist erforderlich.'
			)
		),
		'custom_U1095' => array(
			'order' => 9,
			'type' => 'string',
			'label' => 'Email',
			'required' => true,
			'errors' => array(
				'required' => 'Feld „Email“ ist erforderlich.'
			)
		)
	)
);

process_form($form);
?>
